#!/bin/sh -u
# -u: Treat unset variables as an error when performing parameter expansion.
# If expansion is attempted on an unset interactive, exits with a non-zero status.
#
# Process executed before application manager execution
#
# Author: Loan Lassalle <https://github.com/lassalleloan>

# Current version of StevenBlack/hosts source files
CURRENT_VERSION="$(sed -En 's/^# CURRENT_VERSION=([0-9]+([.][0-9]+)*)$/\1/p' env.list)"

# Default verbosity level
VERBOSITY="$(sed -En 's/^# VERBOSITY=([0-9]{1})$/\1/p' env.list)"

# Display a banner
banner() {
  printf "Pre-run script\n"
}

# Usage of the script
usage() {
  printf "Usage: pre-run [--verbosity (0 | 1 | 2)]\n"
  printf "\n"
  printf "Process executed before run-app execution\n"
  printf "\n"
  printf "Version: 1.0.0, build deadbeef\n"
  printf "\n"
  printf "Author:\n"
  printf "  Loan Lassalle - <https://github.com/lassalleloan>\n"
  printf "\n"
  printf "Options:\n"
  printf "  -v, --verbosity (0 | 1 | 2)     Level of verbosity: no ouput, step information, interactive\n"
  printf "  -h, --help                      Help on how to use this script\n"
}

# Check for updates
check_updates() {
  local current_version="$1"
  local verbosity="$2"

  if [ "$verbosity" -ne 0 ]; then
    printf "Checking for updates\n"
  fi

  # Retrieve the version number
  local new_version="$(curl --silent https://raw.githubusercontent.com/StevenBlack/hosts/master/package.json | \
    sed -En 's/^[ ]*"version": "([0-9]+([.][0-9]+)*)",$/\1/p')"

  if [ "$verbosity" -eq 2 ]; then
    printf "Current version: %*s\n" 12 "$current_version"
    printf "New version: %*s\n" 16 "$new_version"
  fi

  if [ ! -f src/hosts ] || \
    [ ! -s src/hosts ] || \
    [ "$(printf '%s\n' "$current_version" "$new_version" | sort -rV | head -n 1)" != "$current_version" ]; then

    # Edit CURRENT_VERSION & LAST_UPDATE_ON variables in env.list file
    sed -i '' -E "s/^# CURRENT_VERSION=$current_version$/# CURRENT_VERSION=$new_version/" env.list
    sed -i '' -E "s/^# LAST_UPDATE_ON=[12]([0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(0[0-9]|1[0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])Z$/# LAST_UPDATE_ON=$(date -u +%FT%TZ)/" env.list
  else

    # Stop all future process
    exit 1
  fi
}

# Check if it is an integer
exit_if_not_integer() {
  local variable="$1"

  if ! echo "$variable" | grep -Eq  "^[0-9]{1}$"; then
    printf "%s: not a integer\n" "$variable"
    usage
    exit 1
  fi
}

# Main
for arg in "$@"; do
  shift
  case "$arg" in
    "--verbosity")
      set -- "$@" "-v"
      ;;
    "--help")
      set -- "$@" "-h"
      ;;
    "--"*)
      set -- "$@" "-?"
      ;;
    *)
      set -- "$@" "$arg"
  esac
done

while getopts ":v:h" option; do
  case $option in
    v)
      VERBOSITY=$OPTARG
      exit_if_not_integer "$VERBOSITY"
      ;;
    h)
      usage
      exit
      ;;
    :)
      printf "%s: argument required\n" "$OPTARG"
      exit 1
      ;;
    \?)
      printf "%s: invalid option\n" "$OPTARG"
      usage
      exit 1
      ;;
  esac
done

if [ "$VERBOSITY" -ne 0 ]; then
  banner
fi

# Check for updates
check_updates "$CURRENT_VERSION" "$VERBOSITY"
