#!/bin/sh -u
# -u: Treat unset variables as an error when performing parameter expansion.
# If expansion is attempted on an unset interactive, exits with a non-zero status.
#
# Manage the dns-black-hole app
#
# Author: Loan Lassalle <https://github.com/lassalleloan>

# Start Docker application
DOCKER_WAS_RUNNING=false

# Image tag and container name
IMAGE_TAG="dns-black-hole"
CONTAINER_NAME="$IMAGE_TAG"

# Working directory
WORKING_DIRECTORY="$(sed -En 's/^# WORKING_DIRECTORY=(\/[^ #]+)[ #]?.*$/\1/p' env.list)"

# Source and destination directories for the Docker container"s volume
SRC_VOLUME_1="$WORKING_DIRECTORY/src/hosts"
DST_VOLUME_1="/dns-black-hole/etc/hosts"

SRC_VOLUME_2="$WORKING_DIRECTORY/src/blacklist"
DST_VOLUME_2="/dns-black-hole/hosts-master/blacklist"

SRC_VOLUME_3="$WORKING_DIRECTORY/src/whitelist"
DST_VOLUME_3="/dns-black-hole/hosts-master/whitelist"

SRC_VOLUME_4="$WORKING_DIRECTORY/src/myhosts"
DST_VOLUME_4="/dns-black-hole/hosts-master/myhosts"

# Processing mode (default: detach)
INTERACTIVE=false
DETACH=false

# Bypass any prior checking
FORCE=false

# Remove all unused Docker data
PRUNE=false

# Remove all Docker data
WIPEOUT=false

# Default verbosity level
VERBOSITY="$(sed -En 's/^# VERBOSITY=([0-9]{1})$/\1/p' env.list)"

# Display a banner
banner() {
  printf "     _             _    _         _       _        _                      \n"
  printf "  __| |_ _  ______| |__| |__ _ __| |_____| |_  ___| |___   __ _ _ __ _ __ \n"
  printf " / _\` | ' \(_-<___| '_ \ / _\` / _| / /___| ' \/ _ \ / -_) / _\` | '_ \ '_ \ \n"
  printf " \__,_|_||_/__/   |_.__/_\__,_\__|_\_\   |_||_\___/_\___| \__,_| .__/ .__/\n"
  printf "                                                               |_|  |_|   \n"
}

# Usage of the script
usage() {
  printf "Usage: run-app [--interactive | --detach --force --verbosity (0 | 1 | 2) | --prune --verbosity (0 | 1 | 2) | --wipeout --verbosity (0 | 1 | 2)]\n"
  printf "\n"
  printf "Manage the dns-black-hole app\n"
  printf "\n"
  printf "Version: 1.0.0, build deadbeef\n"
  printf "\n"
  printf "Author:\n"
  printf "  Loan Lassalle - <https://github.com/lassalleloan>\n"
  printf "\n"
  printf "Options:\n"
  printf "  -i, --interactive               Keep stdin open even if not attached and allocate a pseudo-tty\n"
  printf "  -d, --detach                    Leave the container running in the background (default processing mode)\n"
  printf "  -f, --force                     Force the application to run, bypass any prior checking\n"
  printf "  -p, --prune                     Remove all unused Docker data\n"
  printf "  -w, --wipeout                   Remove all Docker data\n"
  printf "  -v, --verbosity (0 | 1 | 2)     Level of verbosity: no ouput, step information, interactive\n"
  printf "  -h, --help                      Help on how to use this script\n"
}

# Start Docker application
start_docker() {
  local verbosity="$1"

  if [ "$verbosity" -ne 0 ]; then
    printf "Starting Docker application\n"
  fi

  if docker info >/dev/null 2>&1; then
    DOCKER_WAS_RUNNING=true
  else
    open --background -a Docker

    while ! docker system info > /dev/null 2>&1; do
      sleep 30
    done
  fi
}

# Stop Docker application
stop_docker() {
  local verbosity="$1"

  if [ "$verbosity" -ne 0 ]; then
    printf "Stopping Docker application\n"
  fi

  if [ "$DOCKER_WAS_RUNNING" = false ]; then
    killall Docker > /dev/null 2>&1
  fi
}

# Build Docker container
build_container() {
  local image_tag="$1"
  local container_name="$2"
  local verbosity="$3"

  if [ "$verbosity" -ne 0 ]; then
    printf "Building %s Docker container\n" "$container_name"
  fi

  if [ "$verbosity" -eq 2 ]; then
    docker build --force-rm --tag "$image_tag" .
  else
    docker build --force-rm --quiet --tag "$image_tag" . >/dev/null 2>&1
  fi
}

# Start Docker container
start_container() {
  local image_tag="$1"
  local container_name="$2"
  local src_directory_1="$3"
  local dst_directory_1="$4"
  local src_directory_2="$5"
  local dst_directory_2="$6"
  local src_directory_3="$7"
  local dst_directory_3="$8"
  local src_directory_4="$9"
  local dst_directory_4="${10}"
  local interactive="${11}"
  local verbosity="${12}"

  if [ "$verbosity" -ne 0 ]; then
    printf "Starting %s Docker container\n" "$container_name"
  fi

  if [ "$interactive" = true ]; then
    docker run \
      --interactive \
      --entrypoint "sh" \
      --env-file env.list \
      --name "$container_name" \
      --rm \
      --tty \
      --volume "$src_directory_1":"$dst_directory_1" \
      --volume "$src_directory_2":"$dst_directory_2" \
      --volume "$src_directory_3":"$dst_directory_3" \
      --volume "$src_directory_4":"$dst_directory_4" \
      "$image_tag"
  else
    if [ "$verbosity" -eq 2 ]; then
      docker run \
        --env-file env.list \
        --name "$container_name" \
        --rm \
        --volume "$src_directory_1":"$dst_directory_1" \
        --volume "$src_directory_2":"$dst_directory_2" \
        --volume "$src_directory_3":"$dst_directory_3" \
        --volume "$src_directory_4":"$dst_directory_4" \
        "$image_tag"
    else
      docker run \
        --env-file env.list \
        --name "$container_name" \
        --rm \
        --volume "$src_directory_1":"$dst_directory_1" \
        --volume "$src_directory_2":"$dst_directory_2" \
        --volume "$src_directory_3":"$dst_directory_3" \
        --volume "$src_directory_4":"$dst_directory_4" \
        "$image_tag" >/dev/null 2>&1
    fi
  fi
}

# Stop Docker container
stop_container() {
  local container_name="$1"
  local verbosity="$2"

  if [ "$verbosity" -ne 0 ]; then
    printf "Stopping %s Docker container\n" "$container_name"
  fi

  if [ "$verbosity" -eq 2 ]; then
    docker stop "$container_name"
  else
    docker stop "$container_name" >/dev/null 2>&1
  fi
}

# Kill Docker container
kill_container() {
  local container_name="$1"
  local verbosity="$2"

  if [ "$verbosity" -ne 0 ]; then
    printf "Killing %s Docker container\n" "$container_name"
  fi

  if [ "$verbosity" -eq 2 ]; then
    docker kill "$container_name"
  else
    docker kill "$container_name" >/dev/null 2>&1
  fi
}

# Remove Docker container
remove_container() {
  local container_name="$1"
  local verbosity="$2"

  if [ "$verbosity" -ne 0 ]; then
    printf "Removing %s Docker container\n" "$container_name"
  fi

  if [ "$verbosity" -eq 2 ]; then
    docker rm --volumes "$container_name"
  else
    docker rm --force --volumes "$container_name" >/dev/null 2>&1
  fi
}

# Remove Docker volume
remove_volume() {
  local volume_name="$1"
  local verbosity="$2"

  if [ "$verbosity" -ne 0 ]; then
    printf "Removing %s Docker volume\n" "$volume_name"
  fi

  if [ "$verbosity" -eq 2 ]; then
    docker volume rm "$volume_name"
  else
    docker volume rm --force "$volume_name" >/dev/null 2>&1
  fi
}

# Remove unused Docker volumes
remove_volumes_unused() {
  local verbosity="$1"

  if [ "$verbosity" -ne 0 ]; then
    printf "Removing unused Docker volumes\n"
  fi

  if [ "$verbosity" -eq 2 ]; then
    docker volume prune
  else
    docker volume prune --force >/dev/null 2>&1
  fi
}

# Remove Docker image
remove_image() {
  local image_name="$1"
  local verbosity="$2"

  if [ "$verbosity" -ne 0 ]; then
    printf "Removing %s Docker image\n" "$image_name"
  fi

  if [ "$verbosity" -eq 2 ]; then
    docker image rm "$image_name"
  else
    docker image rm --force "$image_name" >/dev/null 2>&1
  fi
}

# Remove unused Docker images
remove_images_unused() {
  local verbosity="$1"

  if [ "$verbosity" -ne 0 ]; then
    printf "Removing unused Docker images\n"
  fi

  if [ "$verbosity" -eq 2 ]; then
    docker image prune --all
  else
    docker image prune --all --force >/dev/null 2>&1
  fi
}

# Remove all unused Docker data
remove_all_unused() {
  local verbosity="$1"

  if [ "$verbosity" -ne 0 ]; then
    printf "Removing all unused Docker data\n"
  fi

  if [ "$verbosity" -eq 2 ]; then
    docker system prune --all --volumes
  else
    docker system prune --all --force --volumes >/dev/null 2>&1
  fi
}

# Remove all Docker data
remove_all() {
  local verbosity="$1"

  if [ "$verbosity" -ne 0 ]; then
    printf "Removing all Docker data\n"
  fi

  # Stop all containers
  stop_container "$(docker ps --all --quiet)" "$verbosity"

  # Kill all containers
  kill_container "$(docker ps --all --quiet)" "$verbosity"

  # Remove all containers
  remove_container "$(docker ps --all --quiet)" "$verbosity"

  # Remove all volumes
  remove_volume "$(docker volume ls --quiet)" "$verbosity"

  # Remove all images
  remove_image "$(docker image ls --all --quiet)" "$verbosity"
}

# Check if it is an integer
exit_if_not_integer() {
  local variable="$1"

  if ! echo "$variable" | grep -Eq  "^[0-9]{1}$"; then
    printf "%s: not a integer\n" "$variable"
    usage
    exit 1
  fi
}

# Main
for arg in "$@"; do
  shift
  case "$arg" in
    "--interactive")
      set -- "$@" "-i"
      ;;
    "--detach")
      set -- "$@" "-d"
      ;;
    "--force")
      set -- "$@" "-f"
      ;;
    "--prune")
      set -- "$@" "-p"
      ;;
    "--wipeout")
      set -- "$@" "-w"
      ;;
    "--verbosity")
      set -- "$@" "-v"
      ;;
    "--help")
      set -- "$@" "-h"
      ;;
    "--"*)
      set -- "$@" "-?"
      ;;
    *)
      set -- "$@" "$arg"
  esac
done

while getopts ":idfpwv:h" option; do
  case $option in
    i)
      INTERACTIVE=true
      ;;
    d)
      DETACH=true
      ;;
    f)
      FORCE=true
      ;;
    p)
      PRUNE=true
      ;;
    w)
      WIPEOUT=true
      ;;
    v)
      VERBOSITY=$OPTARG
      exit_if_not_integer "$VERBOSITY"
      ;;
    h)
      usage
      exit
      ;;
    :)
      printf "%s: argument required\n" "$OPTARG"
      exit 1
      ;;
    \?)
      printf "%s: invalid option\n" "$OPTARG"
      usage
      exit 1
      ;;
  esac
done

if { [ "$INTERACTIVE" = true ] || [ "$DETACH" = true ] && { [ "$PRUNE" = true ] || [ "$WIPEOUT" = true ]; } } \
  || { { [ "$INTERACTIVE" = true ] || [ "$PRUNE" = true ] || [ "$WIPEOUT" = true ]; } && [ "$DETACH" = true ]; }; then
  printf -- "--interactive --detach --prune --wipeout: options must be used separately\n"
  usage
  exit 1
elif [ "$INTERACTIVE" = true ] || [ "$PRUNE" = true ] || [ "$WIPEOUT" = true ] && [ "$FORCE" = true ]; then
  printf -- "--force: option must be used with --detach option\n"
  usage
  exit 1
elif [ "$PRUNE" = true ]; then

  Start Docker application
  start_docker "$VERBOSITY"

  remove_all_unused "$VERBOSITY"

  # Stop Docker application
  stop_docker "$VERBOSITY"

  exit 0
elif [ "$WIPEOUT" = true ]; then

  # Start Docker application
  start_docker "$VERBOSITY"

  remove_unused "$VERBOSITY"

  # Stop Docker application
  stop_docker "$VERBOSITY"

  exit 0
else
  if [ "$INTERACTIVE" = true ]; then
    VERBOSITY=2
  fi

  if [ "$VERBOSITY" -ne 0 ]; then
    banner
  fi

  # Pre-run script
  if [ "$FORCE" = false ]; then
    printf "\n"
    if ! sh pre-run -v "$VERBOSITY"; then
      exit 0
    fi
  fi

  # Run script
  if [ "$VERBOSITY" -ne 0 ]; then
    printf "\n"
    printf "Run script\n"
  fi
  
  # Start Docker application
  start_docker "$VERBOSITY"

  # Build Docker container
  if ! build_container "$IMAGE_TAG" "$CONTAINER_NAME" "$VERBOSITY"; then
    exit 1
  fi
  
  # Start Docker container
  if ! start_container "$IMAGE_TAG" "$CONTAINER_NAME" \
    "$SRC_VOLUME_1" "$DST_VOLUME_1" \
    "$SRC_VOLUME_2" "$DST_VOLUME_2" \
    "$SRC_VOLUME_3" "$DST_VOLUME_3" \
    "$SRC_VOLUME_4" "$DST_VOLUME_4" \
    "$INTERACTIVE" "$VERBOSITY"; then
    exit 1
  fi
  
  # Remove all related data to this container
  stop_container "$CONTAINER_NAME" "$VERBOSITY"
  kill_container "$CONTAINER_NAME" "$VERBOSITY"
  remove_container "$CONTAINER_NAME" "$VERBOSITY"
  remove_volumes_unused "$VERBOSITY"
  remove_images_unused "$VERBOSITY"

  # Stop Docker application
  stop_docker "$VERBOSITY"

  # Post-run script
  printf "\n"
  sh post-run -v "$VERBOSITY"
fi
