#!/bin/sh -u
# -u: Treat unset variables as an error when performing parameter expansion.
# If expansion is attempted on an unset interactive, exits with a non-zero status.
#
# Set the launch agent for dns-black-hole update
#
# Author: Loan Lassalle <https://github.com/lassalleloan>

# Source directory for agent
AGENT_SRC_DIRECTORY="$(sed -En 's/^# AGENT_SRC_DIRECTORY=([^ #]+)/\1/p' env.list)"

mkdir -p ~/Library/LaunchAgents
cp "$AGENT_SRC_DIRECTORY"/com.loanlassalle.dns-black-hole.update.plist ~/Library/LaunchAgents
launchctl load ~/Library/LaunchAgents/com.loanlassalle.dns-black-hole.update.plist
launchctl start com.loanlassalle.dns-black-hole.update
