#!/bin/sh -u
# -u: Treat unset variables as an error when performing parameter expansion.
# If expansion is attempted on an unset interactive, exits with a non-zero status.
#
# Set the dns-black-hole update agent
#
# Author: Loan Lassalle <https://github.com/lassalleloan>

# Working directory
WORKING_DIRECTORY="$(sed -En 's/^# WORKING_DIRECTORY=(\/[^ #]+)[ #]?.*$/\1/p' env.list)"

# Default verbosity level
VERBOSITY="$(sed -En 's/^# VERBOSITY=([0-9]{1})[ #]?.*$/\1/p' env.list)"

# Display a banner
banner() {
  printf "Set-agent script\n"
}

# Usage of the script
usage() {
  printf "Usage: set-agent [--verbosity (0 | 1 | 2)]\n"
  printf "\n"
  printf "Set the dns-black-hole update agent\n"
  printf "\n"
  printf "Version: 1.0.0, build deadbeef\n"
  printf "\n"
  printf "Author:\n"
  printf "  Loan Lassalle - <https://github.com/lassalleloan>\n"
  printf "\n"
  printf "Options:\n"
  printf "  -v, --verbosity (0 | 1 | 2)     Level of verbosity: no ouput, step information, interactive\n"
  printf "  -h, --help                      Help on how to use this script\n"
}

# Create the property list file
create_plist() {
  local verbosity="$1"

  if [ "$verbosity" -ne 0 ]; then
    printf "Creating the property list file\n"
  fi

  # Copy the plist.example file
  if [ "$verbosity" -eq 2 ]; then
    cp "$WORKING_DIRECTORY/agent/com.loanlassalle.dns-black-hole.update.plist.example" \
      "$WORKING_DIRECTORY/agent/com.loanlassalle.dns-black-hole.update.plist"
  else
    cp "$WORKING_DIRECTORY/agent/com.loanlassalle.dns-black-hole.update.plist.example" \
      "$WORKING_DIRECTORY/agent/com.loanlassalle.dns-black-hole.update.plist" > /dev/null 2>&1
  fi

  # Edit the working directory in property list file
  sed -i '' -E "s/<absolute-path>/$WORKING_DIRECTORY/" \
    "$WORKING_DIRECTORY/agent/com.loanlassalle.dns-black-hole.update.plist"

  # Edit debugging outputs in property list file
  if [ "$verbosity" -eq 2 ]; then

    # Delete XML comments at the 32th and 37th line
    sed -i '' '32d;37d' "$WORKING_DIRECTORY/agent/com.loanlassalle.dns-black-hole.update.plist"

    # Change the 8-space tab from 32nd line to 35th line
    sed -i '' '32,35s/            /        /' \
      "$WORKING_DIRECTORY/agent/com.loanlassalle.dns-black-hole.update.plist"
  else

    # Delete XML comments from 28nd line to 38th line
    sed -i '' '28,38d' "$WORKING_DIRECTORY/agent/com.loanlassalle.dns-black-hole.update.plist"
  fi
}

# Copy the property list file
copy_plist() {
  local verbosity="$1"

  if [ "$verbosity" -ne 0 ]; then
    printf "Copying the property list file\n"
  fi

  if [ "$verbosity" -eq 2 ]; then

    # User-provided agent directory
    mkdir -p ~/Library/LaunchAgents
    cp "$WORKING_DIRECTORY/agent/com.loanlassalle.dns-black-hole.update.plist" ~/Library/LaunchAgents
  else

    # User-provided agent directory
    mkdir -p ~/Library/LaunchAgents > /dev/null 2>&1
    cp "$WORKING_DIRECTORY/agent/com.loanlassalle.dns-black-hole.update.plist" \
      ~/Library/LaunchAgents > /dev/null 2>&1
  fi
}

# Load the property list file
load_plist() {
  local verbosity="$1"

  if [ "$verbosity" -ne 0 ]; then
    printf "Loading the property list file\n"
  fi

  # Load the job while also marking the job as "not disabled"
  # The job will restart on the next login/reboot.
  launchctl load -w ~/Library/LaunchAgents/com.loanlassalle.dns-black-hole.update.plist > /dev/null 2>&1
}

# Check if it is an integer
exit_if_not_integer() {
  local variable="$1"

  if ! echo "$variable" | grep -Eq  "^[0-9]{1}$"; then
    printf "%s: not a integer\n" "$variable"
    usage
    exit 1
  fi
}

# Main
for arg in "$@"; do
  shift
  case "$arg" in
    "--verbosity")
      set -- "$@" "-v"
      ;;
    "--help")
      set -- "$@" "-h"
      ;;
    "--"*)
      set -- "$@" "-?"
      ;;
    *)
      set -- "$@" "$arg"
  esac
done

while getopts ":v:h" option; do
  case $option in
    v)
      VERBOSITY=$OPTARG
      exit_if_not_integer "$VERBOSITY"
      ;;
    h)
      usage
      exit
      ;;
    :)
      printf "%s: argument required\n" "$OPTARG"
      exit 1
      ;;
    \?)
      printf "%s: invalid option\n" "$OPTARG"
      usage
      exit 1
      ;;
  esac
done

if [ "$VERBOSITY" -ne 0 ]; then
  banner
fi

create_plist "$VERBOSITY"
# copy_plist "$VERBOSITY"
# load_plist "$VERBOSITY"
